
spring:
  datasource:
    name: test
    url: jdbc:mysql://39.97.248.91:3306/mydatabase?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:/static/
  mvc:
    static-path-pattern: /**

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.homestay.pojo
  configuration:
    map-underscore-to-camel-case: true